Repository DeveloperAcademy-POSTECH/MC3-Team13-RiceCake, pull requests merged in 2022-07, with the labels that each got.

#1 Feature/home view
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Assets.xcassets/AppIcon.appiconset/Contents.json
  RiceCake/RiceCake/Base.lproj/Main.storyboard
  RiceCake/RiceCake/HomeView/Base.lproj/Main.storyboard
  RiceCake/RiceCake/HomeView/HomeViewController.swift
  RiceCake/RiceCake/ViewController.swift
Labels: enhancement

#9 feat: 디바이스 방향 고정
  RiceCake/RiceCake/AppDelegate.swift
Labels: enhancement

#13 Feat[#12]: GameVC와 BusSeatMissionVC 연결
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/BusSeatMission/BusSeatMission.storyboard
  RiceCake/RiceCake/BusSeatMission/BusSeatMissionViewController.swift
  RiceCake/RiceCake/Game/GameView.storyboard
  RiceCake/RiceCake/Game/GameViewController.swift
Labels: enhancement

#17 Feature/#6 story view
  RiceCake/.swiftlint.yml
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Assets.xcassets/Environment.spriteatlas/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Environment.spriteatlas/busFloor.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Environment.spriteatlas/busFloor.imageset/busFloor.png
  RiceCake/RiceCake/Assets.xcassets/Environment.spriteatlas/busFrame.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Environment.spriteatlas/busFrame.imageset/busFrame.png
  RiceCake/RiceCake/Assets.xcassets/Environment.spriteatlas/busPole.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Environment.spriteatlas/busPole.imageset/busPole.png
  RiceCake/RiceCake/Assets.xcassets/Environment.spriteatlas/busSeat.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Environment.spriteatlas/busSeat.imageset/busSeat.png
  RiceCake/RiceCake/Assets.xcassets/Environment.spriteatlas/road.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Environment.spriteatlas/road.imageset/road.png
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/playerBack.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/playerBack.imageset/playerBack.png
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/playerFront.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/playerFront.imageset/playerFront.png
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/playerLeft.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/playerLeft.imageset/playerLeft.png
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/playerRight.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/playerRight.imageset/playerRight.png
  RiceCake/RiceCake/Assets.xcassets/player.imageset/player.png
  RiceCake/RiceCake/Game/Constants.swift
  RiceCake/RiceCake/Game/GameScene.sks
  RiceCake/RiceCake/Game/GameScene.swift
  RiceCake/RiceCake/Game/GameViewController.swift
Labels: enhancement

#23 Feat[#20]: BusSeatMission에 들어가는 제스쳐들을 추가했습니다. (SpriteKit)
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Assets.xcassets/BusSeatMission/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusSeatMission/busSeatMissionBackground.imageset/48F68A43-379C-43CB-95AB-EB26DEEAE8B6_1_102_o.jpeg
  RiceCake/RiceCake/Assets.xcassets/BusSeatMission/busSeatMissionBackground.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusSeatMission/childRightHand.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusSeatMission/childRightHand.imageset/D6D4B9EF-491A-4D8E-9852-7CBA17A2AD29_4_5005_c.jpeg
  RiceCake/RiceCake/BusSeatMission/BusSeatMissionConstants.swift
  RiceCake/RiceCake/BusSeatMission/BusSeatMissionScene.swift
  RiceCake/RiceCake/Game/GameView.storyboard
  RiceCake/RiceCake/Game/GameViewController.swift
Labels: enhancement

#21 Feature/#16 make bust pole mission view
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/BusPoleMission/BusPoleMission.storyboard
  RiceCake/RiceCake/BusPoleMission/BusPoleMissionViewController.swift
  RiceCake/RiceCake/Game/GameViewController.swift
Labels: enhancement

#25 feat: BusSeatMission 배경 흔들림 효과 추가
  RiceCake/RiceCake/BusSeatMission/BusSeatMissionScene.swift
Labels: enhancement

#26 feat: player 애니메이션 추가
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Assets.xcassets/Environment.spriteatlas/busFrame.imageset/busFrame.png
  RiceCake/RiceCake/Assets.xcassets/Environment.spriteatlas/busSeat.imageset/busSeat.png
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/player1.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/player1.imageset/player1.png
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/player2.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/player2.imageset/player2.png
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/player3.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/player3.imageset/player3.png
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/player4.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/player4.imageset/player4.png
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/player5.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/player5.imageset/player5.png
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/player6.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/player6.imageset/player6.png
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/player7.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/player7.imageset/player7.png
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/playerBack.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/playerBack.imageset/playerBack.png
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/playerFront.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/playerFront.imageset/playerFront.png
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/playerLeft.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/playerLeft.imageset/playerLeft.png
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/playerRight.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Player.spriteatlas/playerRight.imageset/playerRight.png
  RiceCake/RiceCake/Game/ActionList.sks
  RiceCake/RiceCake/Game/GameScene.swift
  RiceCake/RiceCake/Game/GameViewController.swift
  RiceCake/RiceCake/Game/MissionScene.swift
Labels: enhancement

#30 Feature: feature/ 19 make bus handle tab gesture >> BusPoleMission에 탭제스처 구현
  RiceCake/RiceCake/Assets.xcassets/BusPoleMission/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusPoleMission/busHandle.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusPoleMission/busHandle.imageset/busHandle.png
  RiceCake/RiceCake/Assets.xcassets/BusPoleMission/busPoleMissionBackground.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusPoleMission/busPoleMissionBackground.imageset/busPoleMissionBackground.png
  RiceCake/RiceCake/Assets.xcassets/BusPoleMission/childHoldHand.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusPoleMission/childHoldHand.imageset/childHoldHand.png
  RiceCake/RiceCake/Assets.xcassets/BusPoleMission/childLeftHand.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusPoleMission/childLeftHand.imageset/childLeftHand.png
  RiceCake/RiceCake/Assets.xcassets/BusPoleMission/frontBusPole.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusPoleMission/frontBusPole.imageset/frontBusPole.png
  RiceCake/RiceCake/BusPoleMission/BusPoleMission.storyboard
  RiceCake/RiceCake/BusPoleMission/BusPoleMissionViewController.swift
  RiceCake/RiceCake/Game/GameViewController.swift
Labels: enhancement

#32 Feat[#24]: BusSeatMission / 손잡이를 잡은 뒤에 손 부분을 꾹 누르면 흔들림이 멈춥니다
  .github/ISSUE_TEMPLATE/---bug.md
  .github/ISSUE_TEMPLATE/---feature.md
  .github/ISSUE_TEMPLATE/---refactor.md
  RiceCake/RiceCake/BusSeatMission/BusSeatMissionScene.swift
  RiceCake/RiceCake/Game/GameScene.swift
  RiceCake/RiceCake/Game/GameViewController.swift
Labels: enhancement

#33 Feature[#22] BusPoleMission LonPressGesture 구현
  RiceCake/RiceCake/BusPoleMission/BusPoleMission.storyboard
  RiceCake/RiceCake/BusPoleMission/BusPoleMissionViewController.swift
  RiceCake/RiceCake/Game/GameView.storyboard
  RiceCake/RiceCake/Game/GameViewController.swift
Labels: enhancement

#43 Feature/#42 refactor gameview
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Game/GameScene+Extension.swift
  RiceCake/RiceCake/Game/GameScene.swift
  RiceCake/RiceCake/Game/GameViewController.swift
Labels: refactoring

#66 Feature/#64 change stage
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusEnvironment.spriteatlas/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusEnvironment.spriteatlas/busFloor.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusEnvironment.spriteatlas/busFloor.imageset/busFloor.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusEnvironment.spriteatlas/busFrame.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusEnvironment.spriteatlas/busFrame.imageset/busFrame.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusEnvironment.spriteatlas/busPole.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusEnvironment.spriteatlas/busPole.imageset/busPole.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusEnvironment.spriteatlas/busSeat.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusEnvironment.spriteatlas/busSeat.imageset/busSeat.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusEnvironment.spriteatlas/road.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusEnvironment.spriteatlas/road.imageset/road.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusPoleMission/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusPoleMission/busHandle.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusPoleMission/busHandle.imageset/busHandle.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusPoleMission/busPoleMissionBackground.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusPoleMission/busPoleMissionBackground.imageset/busPoleMissionBackground.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusPoleMission/childHoldHand.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusPoleMission/childHoldHand.imageset/childHoldHand.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusPoleMission/childLeftHand.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusPoleMission/childLeftHand.imageset/childLeftHand.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusPoleMission/frontBusPole.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusPoleMission/frontBusPole.imageset/frontBusPole.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusSeatMission/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusSeatMission/busSeatHandle.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusSeatMission/busSeatHandle.imageset/busSeatHandle.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusSeatMission/busSeatMissionBackground.imageset/48F68A43-379C-43CB-95AB-EB26DEEAE8B6_1_102_o.jpeg
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusSeatMission/busSeatMissionBackground.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusSeatMission/childRightHand.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusSeatMission/childRightHand.imageset/childRightHand.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusSeatMission/grabbingHand.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusSeatMission/grabbingHand.imageset/KakaoTalk_Image_2022-07-20-16-12-30.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/Contents.json
  RiceCake/RiceCake/Assets.xcassets/StageView/cafe.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/StageView/cafe.imageset/cafe.jpg
  RiceCake/RiceCake/Game/BusStage/BusMission/BusMission.storyboard
  RiceCake/RiceCake/Game/BusStage/BusMission/BusMissionViewController.swift
  RiceCake/RiceCake/Game/BusStage/BusMission/BusPoleMission/BusPoleMission.storyboard
  RiceCake/RiceCake/Game/BusStage/BusMission/BusPoleMission/BusPoleMissionViewController.swift
  RiceCake/RiceCake/Game/BusStage/BusMission/BusSeatMission/BusSeatMission.storyboard
  RiceCake/RiceCake/Game/BusStage/BusMission/BusSeatMission/BusSeatMissionConstants.swift
  RiceCake/RiceCake/Game/BusStage/BusMission/BusSeatMission/BusSeatMissionScene.swift
  RiceCake/RiceCake/Game/BusStage/BusMission/BusSeatMission/BusSeatMissionViewController.swift
  RiceCake/RiceCake/Game/BusStage/BusMission/MissionScene.swift
  RiceCake/RiceCake/Game/BusStage/BusStory/ActionList.sks
  RiceCake/RiceCake/Game/BusStage/BusStory/BusStory.storyboard
  RiceCake/RiceCake/Game/BusStage/BusStory/BusStoryScene+Extension.swift
  RiceCake/RiceCake/Game/BusStage/BusStory/BusStoryScene.swift
  RiceCake/RiceCake/Game/BusStage/BusStory/BusStoryViewController.swift
  RiceCake/RiceCake/Game/BusStage/BusStory/Constants.swift
  RiceCake/RiceCake/Game/BusStage/busStageNotificationCenter.swift
  RiceCake/RiceCake/Game/CafeStage/CafeMission.storyboard
  RiceCake/RiceCake/Game/CafeStage/CafeMissionViewController.swift
  RiceCake/RiceCake/Game/CafeStage/CafeStory.storyboard
  RiceCake/RiceCake/Game/CafeStage/CafeStoryViewController.swift
  RiceCake/RiceCake/Game/GameViewController.swift
  RiceCake/RiceCake/StageView/StageModel.swift
  RiceCake/RiceCake/StageView/StageViewController.swift
Labels: enhancement, refactoring

#67 Feat[#47]: OrderMilkShakeMission을 만들었습니다.
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Assets.xcassets/CafeStage/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/magnifiedMenuBoard.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/magnifiedMenuBoard.imageset/magnifiedMenuBoard.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/menuBoard.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/menuBoard.imageset/IMG_0092.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/orderMilkShakeMissionBackground.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/orderMilkShakeMissionBackground.imageset/IMG_0091.png
  RiceCake/RiceCake/Game/CafeStage/OrderMilkShake/OrderMilkShakeMissionConstants.swift
  RiceCake/RiceCake/Game/CafeStage/OrderMilkShake/OrderMilkShakeScene.swift
Labels: enhancement

#69 Fix[#68]: BusPoleMission / 여러 번 탭했을 때 손이 날아가는 버그 해결
  RiceCake/RiceCake/Game/BusStage/BusMission/BusPoleMission/BusPoleMissionViewController.swift
Labels: bug

#74 Refactor: BusMissionViewController에서 Hint와 Mission을 쉽게 추가할 수 있도록 수정
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Game/BusStage/BusMission/BusMissionViewController.swift
  RiceCake/RiceCake/Game/BusStage/BusMission/HintScene.swift
  RiceCake/RiceCake/Game/BusStage/BusStory/BusStoryScene.swift
  RiceCake/RiceCake/Game/StageNotificationCenter.swift
Labels: refactoring

#75 Fea t[#61] HintView 구현 및 대사를 저장하기 위한 Json 파일 작성
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Hint/HintModel.swift
  RiceCake/RiceCake/Hint/HintScript.json
  RiceCake/RiceCake/Hint/HintView.storyboard
  RiceCake/RiceCake/Hint/HintViewController.swift
  RiceCake/RiceCake/Hint/PaddingLabel.swift
Labels: enhancement

#81 Feat[#62] NoKidsZoneMission 생성 및 제스처 추가
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Assets.xcassets/CafeStage/NoKidsZone/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/NoKidsZone/cafeDoorBackGround.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/NoKidsZone/cafeDoorBackGround.imageset/cafeDoorBackGround.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/NoKidsZone/panelBack.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/NoKidsZone/panelBack.imageset/panelBack.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/NoKidsZone/panelFront.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/NoKidsZone/panelFront.imageset/panelFront.png
  RiceCake/RiceCake/Game/CafeStage/CafeStory/NoKidsZoneMission/NoKidsZoneMission.storyboard
  RiceCake/RiceCake/Game/CafeStage/CafeStory/NoKidsZoneMission/NoKidsZoneMissionViewController.swift
Labels: enhancement

#84 Feature/drink milk shake mission #79
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw0.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw0.imageset/straw0.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw1.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw1.imageset/straw1.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw2.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw2.imageset/straw2.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw3.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw3.imageset/straw3.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw4.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw4.imageset/straw4.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw5.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw5.imageset/straw5.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw6.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw6.imageset/straw6.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw7.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw7.imageset/straw7.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw8.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/DrinkMilkShake/straw8.imageset/straw8.png
  RiceCake/RiceCake/Game/CafeStage/CafeMissionViewController.swift
  RiceCake/RiceCake/Game/CafeStage/DrinkMilkShake/MilkShakeMission.storyboard
  RiceCake/RiceCake/Game/CafeStage/DrinkMilkShake/MilkShakeViewController.swift
  RiceCake/RiceCake/Game/StageNotificationCenter.swift
Labels: refactoring

#82 feat: Sound 적용(MVC)
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Assets.xcassets/Instructment/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Instructment/doubletap.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Instructment/doubletap.imageset/doubletap.png
  RiceCake/RiceCake/Assets.xcassets/Instructment/longPressed.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Instructment/longPressed.imageset/longPressed.png
  RiceCake/RiceCake/Assets.xcassets/Instructment/pan.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Instructment/pan.imageset/pan.png
  RiceCake/RiceCake/Assets.xcassets/Instructment/pinch.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Instructment/pinch.imageset/pinch.png
  RiceCake/RiceCake/Assets.xcassets/Instructment/swipe.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Instructment/swipe.imageset/swipe.png
  RiceCake/RiceCake/Assets.xcassets/Instructment/tap.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/Instructment/tap.imageset/tap.png
  RiceCake/RiceCake/Game/BusStage/BusMission/BusSeatMission/BusSeatMissionScene.swift
  RiceCake/RiceCake/Game/BusStage/BusMission/BusSeatMission/BusSeatMissionViewController.swift
  RiceCake/RiceCake/Model/GuideAsset.swift
  RiceCake/RiceCake/Model/GuideAssetBrain.swift
  RiceCake/RiceCake/Model/Sound.swift
  RiceCake/RiceCake/Model/SoundBrain.swift
  RiceCake/RiceCake/Sounds/Gesture0.wav
  RiceCake/RiceCake/Sounds/Gesture1.wav
  RiceCake/RiceCake/Sounds/Gesture2.wav
  RiceCake/RiceCake/Sounds/Gesture3.wav
  RiceCake/RiceCake/Sounds/Gesture4.wav
  RiceCake/RiceCake/Sounds/Gesture5.wav
  RiceCake/RiceCake/Sounds/Negative.wav
  RiceCake/RiceCake/Sounds/Positive.wav
  RiceCake/RiceCake/Sounds/background.wav
Labels: enhancement

#83 Feat[#49]: BusStationMission을 만들었습니다
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Assets.xcassets/CheckBusMission/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CheckBusMission/background.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CheckBusMission/background.imageset/background.png
  RiceCake/RiceCake/Assets.xcassets/CheckBusMission/leftperson.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CheckBusMission/leftperson.imageset/leftperson.png
  RiceCake/RiceCake/Assets.xcassets/CheckBusMission/leftseat.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CheckBusMission/leftseat.imageset/leftseat.png
  RiceCake/RiceCake/Assets.xcassets/CheckBusMission/rightperson.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CheckBusMission/rightperson.imageset/rightperson.png
  RiceCake/RiceCake/Assets.xcassets/CheckBusMission/rightseat.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CheckBusMission/rightseat.imageset/rightseat.png
  RiceCake/RiceCake/Game/BusStage/BusMission/BusStationMission/BusStationMission.storyboard
  RiceCake/RiceCake/Game/BusStage/BusMission/BusStationMission/BusStationViewController.swift
Labels: enhancement

#87 Feature/#51 bus bell mission
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Assets.xcassets/BusBellMission/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusBellMission/bell.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusBellMission/bell.imageset/bell.png
  RiceCake/RiceCake/Assets.xcassets/BusBellMission/bellSound.dataset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusBellMission/bellSound.dataset/bellSound.mp3
  RiceCake/RiceCake/Assets.xcassets/BusBellMission/busBellMissionBackground.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusBellMission/busBellMissionBackground.imageset/busBellMissionBackground.png
  RiceCake/RiceCake/Assets.xcassets/BusBellMission/pushedBell.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusBellMission/pushedBell.imageset/pushedBell.png
  RiceCake/RiceCake/Game/BusStage/BusMission/BusBellMission/BusBellMission.storyboard
  RiceCake/RiceCake/Game/BusStage/BusMission/BusBellMission/BusBellMissionViewController.swift
Labels: enhancement

#89 Feat[#49]: BusStationMission gesture 순서 변경하였습니다.
  RiceCake/RiceCake/Game/BusStage/BusMission/BusStationMission/BusStationViewController.swift
Labels: enhancement

#90 Feature/#54 inside cafe
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Assets.xcassets/CafeStage/CafeRoadEnvironment/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/CafeRoadEnvironment/cafeRoad.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/CafeRoadEnvironment/cafeRoad.imageset/cafeRoad.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/CafeRoadEnvironment/firstCafe.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/CafeRoadEnvironment/firstCafe.imageset/firstCafe.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/CafeRoadEnvironment/firstCafeDoor.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/CafeRoadEnvironment/firstCafeDoor.imageset/firstCafeDoor.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/CafeRoadEnvironment/secondCafe.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/CafeRoadEnvironment/secondCafe.imageset/secondCafe.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/CafeRoadEnvironment/secondCafeDoor.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/CafeRoadEnvironment/secondCafeDoor.imageset/secondCafeDoor.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/insideCafeEnvironment/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/insideCafeEnvironment/cafeDecoration.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/insideCafeEnvironment/cafeDecoration.imageset/cafeDecoration.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/insideCafeEnvironment/cafeLeftChair.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/insideCafeEnvironment/cafeLeftChair.imageset/cafeLeftChair.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/insideCafeEnvironment/cafeManager.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/insideCafeEnvironment/cafeManager.imageset/cafeManager.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/insideCafeEnvironment/cafeRightChair.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/insideCafeEnvironment/cafeRightChair.imageset/cafeRightChair.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/insideCafeEnvironment/insideCafeChair.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/insideCafeEnvironment/insideCafeChair.imageset/insideCafeChair.png
  RiceCake/RiceCake/Assets.xcassets/CafeStage/insideCafeEnvironment/insideCafeOrder.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/CafeStage/insideCafeEnvironment/insideCafeOrder.imageset/insideCafeOrder.png
  RiceCake/RiceCake/Game/CafeStage/CafeStory/CafeStageConstant.swift
  RiceCake/RiceCake/Game/CafeStage/CafeStory/CafeStoryRoadScene.swift
  RiceCake/RiceCake/Game/CafeStage/CafeStory/InsideCafeScene+Extension.swift
  RiceCake/RiceCake/Game/CafeStage/CafeStory/InsideCafeScene.swift
  RiceCake/RiceCake/Game/CafeStage/CafeStory/InsideFirstCafeScene+Extension.swift
  RiceCake/RiceCake/Game/CafeStage/CafeStory/InsideFirstCafeScene.swift
  RiceCake/RiceCake/Game/CafeStage/CafeStory/InsideSecondCafeScene+Extension.swift
Labels: enhancement

#91 Feature/#77 draw missions and hints by game progress
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Game/BusStage/BusMission/BusBellMission/BusBellMission.storyboard
  RiceCake/RiceCake/Game/BusStage/BusMission/BusBellMission/BusBellMissionViewController.swift
  RiceCake/RiceCake/Game/BusStage/BusMission/BusMissionViewController.swift
  RiceCake/RiceCake/Game/BusStage/BusMission/BusPoleMission/BusPoleMission.storyboard
  RiceCake/RiceCake/Game/BusStage/BusMission/BusSeatMission/BusSeatMission.storyboard
  RiceCake/RiceCake/Game/BusStage/BusMission/BusSeatMission/BusSeatMissionScene.swift
  RiceCake/RiceCake/Game/BusStage/BusMission/BusStationMission/BusStationMission.storyboard
  RiceCake/RiceCake/Game/BusStage/BusMission/BusStationMission/BusStationMissionViewController.swift
  RiceCake/RiceCake/Game/BusStage/BusStory/BusStoryScene.swift
  RiceCake/RiceCake/Game/BusStage/BusStory/BusStoryViewController.swift
  RiceCake/RiceCake/Game/CafeStage/CafeMissionViewController.swift
  RiceCake/RiceCake/Game/StageNotificationCenter.swift
  RiceCake/RiceCake/Hint/HintViewController.swift
Labels: bug, enhancement, refactoring

#94 Fix[#86] 메모리 사용량 해결 및 이미지 추가
  RiceCake/RiceCake/Assets.xcassets/StageView/bus.imageset/bus.jpg
  RiceCake/RiceCake/Assets.xcassets/StageView/cafe.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/StageView/cafe.imageset/cafe.jpg
  RiceCake/RiceCake/Assets.xcassets/stageThumbnail/Contents.json
  RiceCake/RiceCake/Assets.xcassets/stageThumbnail/busStage.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/stageThumbnail/busStage.imageset/busStage.png
  RiceCake/RiceCake/Assets.xcassets/stageThumbnail/cafeStage.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/stageThumbnail/cafeStage.imageset/cafeStage.png
  RiceCake/RiceCake/StageView/StageModel.swift
Labels: bug, enhancement

#95 Feat[#57] 커스텀 폰트 추가 및 적용
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Font/EF_Diary.ttf
  RiceCake/RiceCake/Hint/HintScript.json
  RiceCake/RiceCake/Hint/HintViewController.swift
  RiceCake/RiceCake/HomeView/Base.lproj/Main.storyboard
  RiceCake/RiceCake/Info.plist
  RiceCake/RiceCake/StageView/Stage.storyboard
Labels: enhancement

#97 Feature/#93 connect hints and missions in cafe stage
  RiceCake/RiceCake/Game/CafeStage/CafeMission.storyboard
  RiceCake/RiceCake/Game/CafeStage/CafeMissionViewController.swift
  RiceCake/RiceCake/Game/CafeStage/CafeStory/CafeStoryRoadScene.swift
  RiceCake/RiceCake/Game/CafeStage/CafeStory/CafeStoryViewController.swift
  RiceCake/RiceCake/Game/CafeStage/CafeStory/InsideCafeScene.swift
  RiceCake/RiceCake/Game/CafeStage/CafeStory/NoKidsZoneMission/NoKidsZoneMission.storyboard
  RiceCake/RiceCake/Game/CafeStage/CafeStory/NoKidsZoneMission/NoKidsZoneMissionViewController.swift
  RiceCake/RiceCake/Game/CafeStage/DrinkMilkShake/MilkShakeMission.storyboard
  RiceCake/RiceCake/Game/CafeStage/OrderMilkShake/OrderMilkShakeScene.swift
  RiceCake/RiceCake/Game/StageNotificationCenter.swift
  RiceCake/RiceCake/Hint/HintViewController.swift
Labels: enhancement

#98 Feature/#92 improve game flow
  RiceCake/RiceCake/Game/BusStage/BusMission/BusBellMission/BusBellMissionViewController.swift
  RiceCake/RiceCake/Game/BusStage/BusMission/BusMissionViewController.swift
  RiceCake/RiceCake/Game/BusStage/BusMission/BusPoleMission/BusPoleMissionViewController.swift
  RiceCake/RiceCake/Game/BusStage/BusMission/BusSeatMission/BusSeatMissionScene.swift
  RiceCake/RiceCake/Game/BusStage/BusMission/BusStationMission/BusStationMissionViewController.swift
  RiceCake/RiceCake/Game/CafeStage/CafeMissionViewController.swift
  RiceCake/RiceCake/Game/CafeStage/CafeStory/CafeStoryRoadScene.swift
  RiceCake/RiceCake/Game/CafeStage/CafeStory/InsideCafeScene.swift
  RiceCake/RiceCake/Game/CafeStage/CafeStory/NoKidsZoneMission/NoKidsZoneMissionViewController.swift
  RiceCake/RiceCake/Game/CafeStage/OrderMilkShake/OrderMilkShakeScene.swift
Labels: bug, enhancement

#100 Hotfix/#96 bus pole mission bug
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusPoleMission/childHoldHand.imageset/childHoldHand.png
  RiceCake/RiceCake/Game/BusStage/BusMission/BusPoleMission/BusPoleMissionViewController.swift
Labels: bug, enhancement

#101 Feature/refactor bus stage
  RiceCake/RiceCake.xcodeproj/project.pbxproj
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusBellMission/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusBellMission/bell.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusBellMission/bell.imageset/bell.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusBellMission/bellSound.dataset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusBellMission/bellSound.dataset/bellSound.mp3
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusBellMission/busBellMissionBackground.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusBellMission/busBellMissionBackground.imageset/busBellMissionBackground.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusBellMission/pushedBell.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusBellMission/pushedBell.imageset/pushedBell.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusEnvironment.spriteatlas/busMissionPole.imageset/Contents.json
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusEnvironment.spriteatlas/busMissionPole.imageset/busMissionPole.png
  RiceCake/RiceCake/Assets.xcassets/BusStage/BusEnvironment.spriteatlas/busPole.imageset/busPole.png
  RiceCake/RiceCake/Game/BusStage/BusMission/BusMissionComplete.storyboard
  RiceCake/RiceCake/Game/BusStage/BusMission/BusMissionCompleteViewController.swift
  RiceCake/RiceCake/Game/BusStage/BusMission/BusMissionViewController.swift
  RiceCake/RiceCake/Game/BusStage/BusMission/BusPoleMission/BusPoleMissionViewController.swift
  RiceCake/RiceCake/Game/BusStage/BusStory/BusStageConstants.swift
  RiceCake/RiceCake/Game/BusStage/BusStory/BusStoryScene+Extension.swift
  RiceCake/RiceCake/Game/BusStage/BusStory/BusStoryScene.swift
  RiceCake/RiceCake/Game/StageNotificationCenter.swift
Labels: enhancement, refactoring
